version: '3.8'

services:
  adcontext-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: adcontext-backend-dev
    ports:
      - "8080:8080"
    environment:
      - MEM0_API_KEY=${MEM0_API_KEY}
      - AIHUBMIX_API_KEY=${AIHUBMIX_API_KEY}
      - PYTHONPATH=/app
      - DEBUG=1
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/__pycache__
    restart: unless-stopped
    networks:
      - adcontext-network
    command: ["python", "gateway/main.py", "--host", "0.0.0.0", "--port", "8080", "--log-level", "debug"]

networks:
  adcontext-network:
    driver: bridge